server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/swpbackend?useSSL=false&serverTimezone=UTC
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: haidang71214@gmail.com
    password: ojog ltyu idfa uyaw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  signal-key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9"
